const constants = {
  SUBMIT_FORM: "SUBMIT_FORM",
  ADD_PICTURES: "ADD_PICTURES",
  REMOVE_PICTURES: "REMOVE_PICTURES",
  ADD_BIO: "ADD_BIO",
  ADD_USR_HASHTAG: "ADD_USR_HASHTAG",
  ADD_LIST_HASHTAG: "ADD_LIST_HASHTAG",
  REMOVE_HASHTAG: "REMOVE_HASHTAG",
  MODIFY_ORIENTATION: "MODIFY_ORIENTATION",
  ADD_PARAMETERS: "ADD_PARAMETTERS",
}

export default constants;